apiVersion: v1
kind: LimitRange
metadata:
  name: willo-limitando-recursos
spec:
  limits:
  - default:
      cpu: 1
      memory: 256Mi
    defaultRequest:
      cpu: 0.5
      memory: 128Mi
    type: Container
